apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: sod-app
spec:
  # 3 Pods should exist at all times.
  replicas: 
  selector:
    matchLabels:
      app: sod
  # pod details
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: sod
    spec:
      containers:
      - name: sod
        image: 8001040511/sod-backend:7.0.0
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: PORT 
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: DEBUG 

---

apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-sod
spec:
  ports:
    # Accept traffic sent to port 80
    - name: tcp
      port: 8080
      targetPort: 5000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: sod
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer